patroni_packages:
  - "patroni"
  - "patroni-etcd"
  - "curl"
  - "jq"

patroni_conf_dir: "/etc/patroni"

patroni_log_dir: "/var/log/patroni"
patroni_pg_bin_dir: "/usr/pgsql-{{pg_major}}/bin/"

patroni_use_pgbackrest: yes

patroni_config:
  scope: "flynn"
  namespace: "/the_grid/"
  rest_api_port: "8008"
  ttl: "10"
  loop_wait: "10"
  retry_timeout: "10"
  maximum_lag_on_failover: "1048576"
  postgresql:
    port: "5432"
    listen_address: "0.0.0.0"
    connect_address: "0.0.0.0"
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      work_mem: "8MB"
      maintenance_work_mem: "16MB"
      password_encryption: 'scram-sha-256'

pgbackrest_params:
  archive_command: "pgbackrest --stanza={{patroni_config.scope}} archive-push %p"
  archive_timeout: "60s"