---
- name: Configure the firewall
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items:
    - "{{etcd_cluster.peer_urls_port}}"
    - "{{etcd_cluster.client_url_port}}"
    - "{{patroni_config.rest_api_port}}"
    - "{{patroni_config.postgresql.port}}"
    - "{{haproxy.port_pgsql}}"
    - "{{haproxy.port_stats}}"
    
- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded
